name: (Backends) Pull Request
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref_name || github.run_id }}
  cancel-in-progress: true

jobs:
  qodana:
    name: Qodana
    runs-on: ubuntu-latest
    timeout-minutes: 35
    permissions:
      checks: write
      contents: read
      pull-requests: read
    steps:
      - uses: docker/login-action@v3
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.SPACE_USERNAME }}
          password: ${{ secrets.SPACE_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          artifact-name: qodana-test-backends
          upload-result: true
          use-caches: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TEST_JAVA }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qodana-artifact
          path: ${{ runner.temp }}/qodana/results
